---
title: "Do sand silt and clay sum to 100?"
output: html_notebook
---


a. Stack variables for each depth increment. 
Load variables

Originally from Colby Brungard, ~11/5/2023
Modified 12/8/2023 by T. Nauman to incorporate fixes to rounding errors
```{r}
library(terra)

# Clay
cl0   <- rast("/mnt/disks/sped/ssc_sum/orig_preds/claytotal_r_1x_0_cm_2D_QRFadj.tif")
cl5   <- rast("/mnt/disks/sped/ssc_sum/orig_preds/claytotal_r_1x_5_cm_2D_QRFadj.tif")  
cl15  <- rast("/mnt/disks/sped/ssc_sum/orig_preds/claytotal_r_1x_15_cm_2D_QRFadj.tif")
cl30  <- rast("/mnt/disks/sped/ssc_sum/orig_preds/claytotal_r_1x_30_cm_2D_QRFadj.tif")
cl60  <- rast("/mnt/disks/sped/ssc_sum/orig_preds/claytotal_r_1x_60_cm_2D_QRFadj.tif")
cl100 <- rast("/mnt/disks/sped/ssc_sum/orig_preds/claytotal_r_1x_100_cm_2D_QRFadj.tif")
cl150 <- rast("/mnt/disks/sped/ssc_sum/orig_preds/claytotal_r_1x_150_cm_2D_QRFadj.tif")

# Sand
s0   <- rast("/mnt/disks/sped/ssc_sum/orig_preds/sandtotal_r_1x_0_cm_2D_QRFadj.tif")
s5   <- rast("/mnt/disks/sped/ssc_sum/orig_preds/sandtotal_r_1x_5_cm_2D_QRFadj.tif")  
s15  <- rast("/mnt/disks/sped/ssc_sum/orig_preds/sandtotal_r_1x_15_cm_2D_QRFadj.tif")
s30  <- rast("/mnt/disks/sped/ssc_sum/orig_preds/sandtotal_r_1x_30_cm_2D_QRFadj.tif")
s60  <- rast("/mnt/disks/sped/ssc_sum/orig_preds/sandtotal_r_1x_60_cm_2D_QRFadj.tif")
s100 <- rast("/mnt/disks/sped/ssc_sum/orig_preds/sandtotal_r_1x_100_cm_2D_QRFadj.tif")
s150 <- rast("/mnt/disks/sped/ssc_sum/orig_preds/sandtotal_r_1x_150_cm_2D_QRFadj.tif")

# Silt
si0   <- rast("/mnt/disks/sped/ssc_sum/orig_preds/silttotal_r_1x_0_cm_2D_QRFadj.tif")
si5   <- rast("/mnt/disks/sped/ssc_sum/orig_preds/silttotal_r_1x_5_cm_2D_QRFadj.tif")  
si15  <- rast("/mnt/disks/sped/ssc_sum/orig_preds/silttotal_r_1x_15_cm_2D_QRFadj.tif")
si30  <- rast("/mnt/disks/sped/ssc_sum/orig_preds/silttotal_r_1x_30_cm_2D_QRFadj.tif")
si60  <- rast("/mnt/disks/sped/ssc_sum/orig_preds/silttotal_r_1x_60_cm_2D_QRFadj.tif")
si100 <- rast("/mnt/disks/sped/ssc_sum/orig_preds/silttotal_r_1x_100_cm_2D_QRFadj.tif")
si150 <- rast("/mnt/disks/sped/ssc_sum/orig_preds/silttotal_r_1x_150_cm_2D_QRFadj.tif")
```

Sum each depth increment
```{r}
ssc0 <- c(s0, si0, cl0)
names(ssc0) <- c('sand', 'silt', 'clay')
sum0 <- sum(ssc0)
writeRaster(sum0, "/mnt/disks/sped/ssc_sum/sum0.tif")

ssc5 <- c(s5, si5, cl5)
names(ssc5) <- c('sand', 'silt', 'clay')
sum5 <- sum(ssc5)
writeRaster(sum5, "/mnt/disks/sped/ssc_sum/sum5.tif")

ssc15 <- c(s15, si15, cl15)
names(ssc15) <- c('sand', 'silt', 'clay')
sum15 <- sum(ssc15)
writeRaster(sum15, "/mnt/disks/sped/ssc_sum/sum15.tif")

ssc30 <- c(s30, si30, cl30)
names(ssc30) <- c('sand', 'silt', 'clay')
sum30 <- sum(ssc30)
writeRaster(sum30, "/mnt/disks/sped/ssc_sum/sum30.tif")

ssc60 <- c(s60, si60, cl60)
names(ssc60) <- c('sand', 'silt', 'clay')
sum60 <- sum(ssc60)
writeRaster(sum60, "/mnt/disks/sped/ssc_sum/sum60.tif")

ssc100 <- c(s100, si100, cl100)
names(ssc100) <- c('sand', 'silt', 'clay')
sum100 <- sum(ssc100)
writeRaster(sum100, "/mnt/disks/sped/ssc_sum/sum100.tif")

ssc150 <- c(s150, si150, cl150)
names(ssc150) <- c('sand', 'silt', 'clay')
sum150 <- sum(ssc150)
writeRaster(sum150, "/mnt/disks/sped/ssc_sum/sum150.tif")
```


Normalize predictions to 100% to fix problems
```{r}
#terraOptions(memfrac=0.9, progress=2)
divide_by_sum <- function(vector) {
  # no values sum to 0 (and few that sum to exactly 100), but this is how a check could be incorporated
  #if (sum(vector) == 0) {
    #stop("Sum of the vector is zero. Division by zero is not allowed.")
  #}
  v <- vector / sum(vector)*100
  v2 <- round(v, 0) 
  ## rounding creates occasional sums greater than 100
  ## Errant values are either 99 or 101, so we are correcting by subtracting 1 from
  ## the texture class with the max value for 101 pixels, or adding 1 to the minimum 
  ## texture fraction for sums of 99
  # Create rasters showing where errors are
  sumv2 <- sum(v2)
  sumv2_101 <- sumv2
  sumv2_101[sumv2_101 < 101] <- 0
  sumv2_101[sumv2_101 > 100] <- 1
  sumv2_99 <- sumv2
  sumv2_99[sumv2_99 < 99 | sumv2_99 > 99] <- 0
  sumv2_99[sumv2_99 == 99] <- 1
  ## Reference which fraction is max and min in stacks
  maxv2 <- which.max(v2)
  minv2 <- which.min(v2)
  # maxv2 <- terra::app(v2, which.max)
  # minv2 <- terra::app(v2, which.min)
  ## Create rasters for where clay values should be modified
  claymax <- maxv2
  claymax[claymax < 3] <- 0
  claymax[claymax == 3] <- 1
  claymax <- claymax * sumv2_101
  claymin <- minv2
  claymin[claymin < 3] <- 0
  claymin[claymin == 3] <- 1
  claymin <- claymin * sumv2_99
  ## Create rasters for where silt values should be modified
  siltmax <- maxv2
  siltmax[siltmax < 2 | siltmax > 2] <- 0
  siltmax[siltmax == 2] <- 1
  siltmax <- siltmax * sumv2_101
  siltmin <- minv2
  siltmin[siltmin < 2 | siltmin > 2] <- 0
  siltmin[siltmin == 2] <- 1
  siltmin <- siltmin * sumv2_99
  ## Create rasters for where sand values should be modified
  sandmax <- maxv2
  sandmax[sandmax > 1] <- 0
  sandmax <- sandmax * sumv2_101
  sandmin <- minv2
  sandmin[sandmin > 1] <- 0
  sandmin <- sandmin * sumv2_99
  ## Modify the original rasters
  v2[["clay"]] <- v2[["clay"]]+claymin
  v2[["clay"]] <- v2[["clay"]]-claymax
  v2[["silt"]] <- v2[["silt"]]+siltmin
  v2[["silt"]] <- v2[["silt"]]-siltmax
  v2[["sand"]] <- v2[["sand"]]+sandmin
  v2[["sand"]] <- v2[["sand"]]-sandmax
  return(v2)
}

app(ssc0, divide_by_sum, cores=120, filename= "/mnt/disks/sped/ssc_sum/sum0_fix.tif",
    overwrite=TRUE, wopt=list(datatype='INT1U', names = c('sand', 'silt', 'clay')))
app(ssc5, divide_by_sum, cores=120, filename= "/mnt/disks/sped/ssc_sum/sum5_fix.tif", overwrite=TRUE, wopt=list(datatype='INT1U', names = c('sand', 'silt', 'clay')))
app(ssc15, divide_by_sum, cores=120, filename= "/mnt/disks/sped/ssc_sum/sum15_fix.tif", overwrite=TRUE, wopt=list(datatype='INT1U', names = c('sand', 'silt', 'clay')))
app(ssc30, divide_by_sum, cores=120, filename= "/mnt/disks/sped/ssc_sum/sum30_fix.tif", overwrite=TRUE, wopt=list(datatype='INT1U', names = c('sand', 'silt', 'clay')))
app(ssc60, divide_by_sum, cores=120, filename= "/mnt/disks/sped/ssc_sum/sum60_fix.tif", overwrite=TRUE, wopt=list(datatype='INT1U', names = c('sand', 'silt', 'clay')))
app(ssc100, divide_by_sum, cores=120, filename= "/mnt/disks/sped/ssc_sum/sum100_fix.tif", overwrite=TRUE, wopt=list(datatype='INT1U', names = c('sand', 'silt', 'clay')))
app(ssc150, divide_by_sum, cores=120, filename= "/mnt/disks/sped/ssc_sum/sum150_fix.tif", overwrite=TRUE, wopt=list(datatype='INT1U', names = c('sand', 'silt', 'clay')))

```
